spring:
  application:
    name: discordbot2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.89.249.86:3306/discordBot?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#    url: jdbc:mysql://localhost/discordBot?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  data:
#    redis:
#      # 数据库
#      database: 0
#      # 主机
#      host: 45.76.199.153
#      # 端口
#      port: 6379
#      # 密码
#      password: 123
#      # 读超时
#      timeout: 5s
#      # 连接超时
#      connect-timeout: 5s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
openai:
  api:
    url: https://api.openai.com/v1/chat/completions

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434  # Replace with your Ollama base URL if different
      model-name: mistral  # Replace with your desired model name
      temperature: 0.7
      timeout: 60s
      max-retries: 3










